// Code generated by http://github.com/gojuno/minimock (v3.3.12). DO NOT EDIT.

package mock

//go:generate minimock -i gitlab.ozon.dev/ipogiba/homework/cart/internal/service/cart.ProductService -o product_service_mock.go -n ProductServiceMock -p mock

import (
	"context"
	"gitlab.ozon.dev/ipogiba/homework/cart/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ProductServiceMock implements cart.ProductService
type ProductServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetProductBySKU          func(ctx context.Context, sku model.SKU) (pp1 *model.Product, err error)
	inspectFuncGetProductBySKU   func(ctx context.Context, sku model.SKU)
	afterGetProductBySKUCounter  uint64
	beforeGetProductBySKUCounter uint64
	GetProductBySKUMock          mProductServiceMockGetProductBySKU
}

// NewProductServiceMock returns a mock for cart.ProductService
func NewProductServiceMock(t minimock.Tester) *ProductServiceMock {
	m := &ProductServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetProductBySKUMock = mProductServiceMockGetProductBySKU{mock: m}
	m.GetProductBySKUMock.callArgs = []*ProductServiceMockGetProductBySKUParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProductServiceMockGetProductBySKU struct {
	optional           bool
	mock               *ProductServiceMock
	defaultExpectation *ProductServiceMockGetProductBySKUExpectation
	expectations       []*ProductServiceMockGetProductBySKUExpectation

	callArgs []*ProductServiceMockGetProductBySKUParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// ProductServiceMockGetProductBySKUExpectation specifies expectation struct of the ProductService.GetProductBySKU
type ProductServiceMockGetProductBySKUExpectation struct {
	mock      *ProductServiceMock
	params    *ProductServiceMockGetProductBySKUParams
	paramPtrs *ProductServiceMockGetProductBySKUParamPtrs
	results   *ProductServiceMockGetProductBySKUResults
	Counter   uint64
}

// ProductServiceMockGetProductBySKUParams contains parameters of the ProductService.GetProductBySKU
type ProductServiceMockGetProductBySKUParams struct {
	ctx context.Context
	sku model.SKU
}

// ProductServiceMockGetProductBySKUParamPtrs contains pointers to parameters of the ProductService.GetProductBySKU
type ProductServiceMockGetProductBySKUParamPtrs struct {
	ctx *context.Context
	sku *model.SKU
}

// ProductServiceMockGetProductBySKUResults contains results of the ProductService.GetProductBySKU
type ProductServiceMockGetProductBySKUResults struct {
	pp1 *model.Product
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) Optional() *mProductServiceMockGetProductBySKU {
	mmGetProductBySKU.optional = true
	return mmGetProductBySKU
}

// Expect sets up expected params for ProductService.GetProductBySKU
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) Expect(ctx context.Context, sku model.SKU) *mProductServiceMockGetProductBySKU {
	if mmGetProductBySKU.mock.funcGetProductBySKU != nil {
		mmGetProductBySKU.mock.t.Fatalf("ProductServiceMock.GetProductBySKU mock is already set by Set")
	}

	if mmGetProductBySKU.defaultExpectation == nil {
		mmGetProductBySKU.defaultExpectation = &ProductServiceMockGetProductBySKUExpectation{}
	}

	if mmGetProductBySKU.defaultExpectation.paramPtrs != nil {
		mmGetProductBySKU.mock.t.Fatalf("ProductServiceMock.GetProductBySKU mock is already set by ExpectParams functions")
	}

	mmGetProductBySKU.defaultExpectation.params = &ProductServiceMockGetProductBySKUParams{ctx, sku}
	for _, e := range mmGetProductBySKU.expectations {
		if minimock.Equal(e.params, mmGetProductBySKU.defaultExpectation.params) {
			mmGetProductBySKU.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetProductBySKU.defaultExpectation.params)
		}
	}

	return mmGetProductBySKU
}

// ExpectCtxParam1 sets up expected param ctx for ProductService.GetProductBySKU
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) ExpectCtxParam1(ctx context.Context) *mProductServiceMockGetProductBySKU {
	if mmGetProductBySKU.mock.funcGetProductBySKU != nil {
		mmGetProductBySKU.mock.t.Fatalf("ProductServiceMock.GetProductBySKU mock is already set by Set")
	}

	if mmGetProductBySKU.defaultExpectation == nil {
		mmGetProductBySKU.defaultExpectation = &ProductServiceMockGetProductBySKUExpectation{}
	}

	if mmGetProductBySKU.defaultExpectation.params != nil {
		mmGetProductBySKU.mock.t.Fatalf("ProductServiceMock.GetProductBySKU mock is already set by Expect")
	}

	if mmGetProductBySKU.defaultExpectation.paramPtrs == nil {
		mmGetProductBySKU.defaultExpectation.paramPtrs = &ProductServiceMockGetProductBySKUParamPtrs{}
	}
	mmGetProductBySKU.defaultExpectation.paramPtrs.ctx = &ctx

	return mmGetProductBySKU
}

// ExpectSkuParam2 sets up expected param sku for ProductService.GetProductBySKU
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) ExpectSkuParam2(sku model.SKU) *mProductServiceMockGetProductBySKU {
	if mmGetProductBySKU.mock.funcGetProductBySKU != nil {
		mmGetProductBySKU.mock.t.Fatalf("ProductServiceMock.GetProductBySKU mock is already set by Set")
	}

	if mmGetProductBySKU.defaultExpectation == nil {
		mmGetProductBySKU.defaultExpectation = &ProductServiceMockGetProductBySKUExpectation{}
	}

	if mmGetProductBySKU.defaultExpectation.params != nil {
		mmGetProductBySKU.mock.t.Fatalf("ProductServiceMock.GetProductBySKU mock is already set by Expect")
	}

	if mmGetProductBySKU.defaultExpectation.paramPtrs == nil {
		mmGetProductBySKU.defaultExpectation.paramPtrs = &ProductServiceMockGetProductBySKUParamPtrs{}
	}
	mmGetProductBySKU.defaultExpectation.paramPtrs.sku = &sku

	return mmGetProductBySKU
}

// Inspect accepts an inspector function that has same arguments as the ProductService.GetProductBySKU
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) Inspect(f func(ctx context.Context, sku model.SKU)) *mProductServiceMockGetProductBySKU {
	if mmGetProductBySKU.mock.inspectFuncGetProductBySKU != nil {
		mmGetProductBySKU.mock.t.Fatalf("Inspect function is already set for ProductServiceMock.GetProductBySKU")
	}

	mmGetProductBySKU.mock.inspectFuncGetProductBySKU = f

	return mmGetProductBySKU
}

// Return sets up results that will be returned by ProductService.GetProductBySKU
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) Return(pp1 *model.Product, err error) *ProductServiceMock {
	if mmGetProductBySKU.mock.funcGetProductBySKU != nil {
		mmGetProductBySKU.mock.t.Fatalf("ProductServiceMock.GetProductBySKU mock is already set by Set")
	}

	if mmGetProductBySKU.defaultExpectation == nil {
		mmGetProductBySKU.defaultExpectation = &ProductServiceMockGetProductBySKUExpectation{mock: mmGetProductBySKU.mock}
	}
	mmGetProductBySKU.defaultExpectation.results = &ProductServiceMockGetProductBySKUResults{pp1, err}
	return mmGetProductBySKU.mock
}

// Set uses given function f to mock the ProductService.GetProductBySKU method
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) Set(f func(ctx context.Context, sku model.SKU) (pp1 *model.Product, err error)) *ProductServiceMock {
	if mmGetProductBySKU.defaultExpectation != nil {
		mmGetProductBySKU.mock.t.Fatalf("Default expectation is already set for the ProductService.GetProductBySKU method")
	}

	if len(mmGetProductBySKU.expectations) > 0 {
		mmGetProductBySKU.mock.t.Fatalf("Some expectations are already set for the ProductService.GetProductBySKU method")
	}

	mmGetProductBySKU.mock.funcGetProductBySKU = f
	return mmGetProductBySKU.mock
}

// When sets expectation for the ProductService.GetProductBySKU which will trigger the result defined by the following
// Then helper
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) When(ctx context.Context, sku model.SKU) *ProductServiceMockGetProductBySKUExpectation {
	if mmGetProductBySKU.mock.funcGetProductBySKU != nil {
		mmGetProductBySKU.mock.t.Fatalf("ProductServiceMock.GetProductBySKU mock is already set by Set")
	}

	expectation := &ProductServiceMockGetProductBySKUExpectation{
		mock:   mmGetProductBySKU.mock,
		params: &ProductServiceMockGetProductBySKUParams{ctx, sku},
	}
	mmGetProductBySKU.expectations = append(mmGetProductBySKU.expectations, expectation)
	return expectation
}

// Then sets up ProductService.GetProductBySKU return parameters for the expectation previously defined by the When method
func (e *ProductServiceMockGetProductBySKUExpectation) Then(pp1 *model.Product, err error) *ProductServiceMock {
	e.results = &ProductServiceMockGetProductBySKUResults{pp1, err}
	return e.mock
}

// Times sets number of times ProductService.GetProductBySKU should be invoked
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) Times(n uint64) *mProductServiceMockGetProductBySKU {
	if n == 0 {
		mmGetProductBySKU.mock.t.Fatalf("Times of ProductServiceMock.GetProductBySKU mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetProductBySKU.expectedInvocations, n)
	return mmGetProductBySKU
}

func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) invocationsDone() bool {
	if len(mmGetProductBySKU.expectations) == 0 && mmGetProductBySKU.defaultExpectation == nil && mmGetProductBySKU.mock.funcGetProductBySKU == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetProductBySKU.mock.afterGetProductBySKUCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetProductBySKU.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetProductBySKU implements cart.ProductService
func (mmGetProductBySKU *ProductServiceMock) GetProductBySKU(ctx context.Context, sku model.SKU) (pp1 *model.Product, err error) {
	mm_atomic.AddUint64(&mmGetProductBySKU.beforeGetProductBySKUCounter, 1)
	defer mm_atomic.AddUint64(&mmGetProductBySKU.afterGetProductBySKUCounter, 1)

	if mmGetProductBySKU.inspectFuncGetProductBySKU != nil {
		mmGetProductBySKU.inspectFuncGetProductBySKU(ctx, sku)
	}

	mm_params := ProductServiceMockGetProductBySKUParams{ctx, sku}

	// Record call args
	mmGetProductBySKU.GetProductBySKUMock.mutex.Lock()
	mmGetProductBySKU.GetProductBySKUMock.callArgs = append(mmGetProductBySKU.GetProductBySKUMock.callArgs, &mm_params)
	mmGetProductBySKU.GetProductBySKUMock.mutex.Unlock()

	for _, e := range mmGetProductBySKU.GetProductBySKUMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pp1, e.results.err
		}
	}

	if mmGetProductBySKU.GetProductBySKUMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetProductBySKU.GetProductBySKUMock.defaultExpectation.Counter, 1)
		mm_want := mmGetProductBySKU.GetProductBySKUMock.defaultExpectation.params
		mm_want_ptrs := mmGetProductBySKU.GetProductBySKUMock.defaultExpectation.paramPtrs

		mm_got := ProductServiceMockGetProductBySKUParams{ctx, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetProductBySKU.t.Errorf("ProductServiceMock.GetProductBySKU got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmGetProductBySKU.t.Errorf("ProductServiceMock.GetProductBySKU got unexpected parameter sku, want: %#v, got: %#v%s\n", *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetProductBySKU.t.Errorf("ProductServiceMock.GetProductBySKU got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetProductBySKU.GetProductBySKUMock.defaultExpectation.results
		if mm_results == nil {
			mmGetProductBySKU.t.Fatal("No results are set for the ProductServiceMock.GetProductBySKU")
		}
		return (*mm_results).pp1, (*mm_results).err
	}
	if mmGetProductBySKU.funcGetProductBySKU != nil {
		return mmGetProductBySKU.funcGetProductBySKU(ctx, sku)
	}
	mmGetProductBySKU.t.Fatalf("Unexpected call to ProductServiceMock.GetProductBySKU. %v %v", ctx, sku)
	return
}

// GetProductBySKUAfterCounter returns a count of finished ProductServiceMock.GetProductBySKU invocations
func (mmGetProductBySKU *ProductServiceMock) GetProductBySKUAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProductBySKU.afterGetProductBySKUCounter)
}

// GetProductBySKUBeforeCounter returns a count of ProductServiceMock.GetProductBySKU invocations
func (mmGetProductBySKU *ProductServiceMock) GetProductBySKUBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProductBySKU.beforeGetProductBySKUCounter)
}

// Calls returns a list of arguments used in each call to ProductServiceMock.GetProductBySKU.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetProductBySKU *mProductServiceMockGetProductBySKU) Calls() []*ProductServiceMockGetProductBySKUParams {
	mmGetProductBySKU.mutex.RLock()

	argCopy := make([]*ProductServiceMockGetProductBySKUParams, len(mmGetProductBySKU.callArgs))
	copy(argCopy, mmGetProductBySKU.callArgs)

	mmGetProductBySKU.mutex.RUnlock()

	return argCopy
}

// MinimockGetProductBySKUDone returns true if the count of the GetProductBySKU invocations corresponds
// the number of defined expectations
func (m *ProductServiceMock) MinimockGetProductBySKUDone() bool {
	if m.GetProductBySKUMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetProductBySKUMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetProductBySKUMock.invocationsDone()
}

// MinimockGetProductBySKUInspect logs each unmet expectation
func (m *ProductServiceMock) MinimockGetProductBySKUInspect() {
	for _, e := range m.GetProductBySKUMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProductServiceMock.GetProductBySKU with params: %#v", *e.params)
		}
	}

	afterGetProductBySKUCounter := mm_atomic.LoadUint64(&m.afterGetProductBySKUCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetProductBySKUMock.defaultExpectation != nil && afterGetProductBySKUCounter < 1 {
		if m.GetProductBySKUMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ProductServiceMock.GetProductBySKU")
		} else {
			m.t.Errorf("Expected call to ProductServiceMock.GetProductBySKU with params: %#v", *m.GetProductBySKUMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetProductBySKU != nil && afterGetProductBySKUCounter < 1 {
		m.t.Error("Expected call to ProductServiceMock.GetProductBySKU")
	}

	if !m.GetProductBySKUMock.invocationsDone() && afterGetProductBySKUCounter > 0 {
		m.t.Errorf("Expected %d calls to ProductServiceMock.GetProductBySKU but found %d calls",
			mm_atomic.LoadUint64(&m.GetProductBySKUMock.expectedInvocations), afterGetProductBySKUCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProductServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetProductBySKUInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProductServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProductServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetProductBySKUDone()
}
