// Code generated by http://github.com/gojuno/minimock (v3.3.12). DO NOT EDIT.

package mock

//go:generate minimock -i route256/loms/internal/service/stock.IStockRepo -o stock_repo_mock.go -n StockRepoMock -p mock

import (
	"context"
	"route256/loms/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// StockRepoMock implements stock.IStockRepo
type StockRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetStockBySKU          func(ctx context.Context, sku model.SKU) (sp1 *model.Stock, err error)
	inspectFuncGetStockBySKU   func(ctx context.Context, sku model.SKU)
	afterGetStockBySKUCounter  uint64
	beforeGetStockBySKUCounter uint64
	GetStockBySKUMock          mStockRepoMockGetStockBySKU
}

// NewStockRepoMock returns a mock for stock.IStockRepo
func NewStockRepoMock(t minimock.Tester) *StockRepoMock {
	m := &StockRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetStockBySKUMock = mStockRepoMockGetStockBySKU{mock: m}
	m.GetStockBySKUMock.callArgs = []*StockRepoMockGetStockBySKUParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStockRepoMockGetStockBySKU struct {
	optional           bool
	mock               *StockRepoMock
	defaultExpectation *StockRepoMockGetStockBySKUExpectation
	expectations       []*StockRepoMockGetStockBySKUExpectation

	callArgs []*StockRepoMockGetStockBySKUParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// StockRepoMockGetStockBySKUExpectation specifies expectation struct of the IStockRepo.GetStockBySKU
type StockRepoMockGetStockBySKUExpectation struct {
	mock      *StockRepoMock
	params    *StockRepoMockGetStockBySKUParams
	paramPtrs *StockRepoMockGetStockBySKUParamPtrs
	results   *StockRepoMockGetStockBySKUResults
	Counter   uint64
}

// StockRepoMockGetStockBySKUParams contains parameters of the IStockRepo.GetStockBySKU
type StockRepoMockGetStockBySKUParams struct {
	ctx context.Context
	sku model.SKU
}

// StockRepoMockGetStockBySKUParamPtrs contains pointers to parameters of the IStockRepo.GetStockBySKU
type StockRepoMockGetStockBySKUParamPtrs struct {
	ctx *context.Context
	sku *model.SKU
}

// StockRepoMockGetStockBySKUResults contains results of the IStockRepo.GetStockBySKU
type StockRepoMockGetStockBySKUResults struct {
	sp1 *model.Stock
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) Optional() *mStockRepoMockGetStockBySKU {
	mmGetStockBySKU.optional = true
	return mmGetStockBySKU
}

// Expect sets up expected params for IStockRepo.GetStockBySKU
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) Expect(ctx context.Context, sku model.SKU) *mStockRepoMockGetStockBySKU {
	if mmGetStockBySKU.mock.funcGetStockBySKU != nil {
		mmGetStockBySKU.mock.t.Fatalf("StockRepoMock.GetStockBySKU mock is already set by Set")
	}

	if mmGetStockBySKU.defaultExpectation == nil {
		mmGetStockBySKU.defaultExpectation = &StockRepoMockGetStockBySKUExpectation{}
	}

	if mmGetStockBySKU.defaultExpectation.paramPtrs != nil {
		mmGetStockBySKU.mock.t.Fatalf("StockRepoMock.GetStockBySKU mock is already set by ExpectParams functions")
	}

	mmGetStockBySKU.defaultExpectation.params = &StockRepoMockGetStockBySKUParams{ctx, sku}
	for _, e := range mmGetStockBySKU.expectations {
		if minimock.Equal(e.params, mmGetStockBySKU.defaultExpectation.params) {
			mmGetStockBySKU.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetStockBySKU.defaultExpectation.params)
		}
	}

	return mmGetStockBySKU
}

// ExpectCtxParam1 sets up expected param ctx for IStockRepo.GetStockBySKU
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) ExpectCtxParam1(ctx context.Context) *mStockRepoMockGetStockBySKU {
	if mmGetStockBySKU.mock.funcGetStockBySKU != nil {
		mmGetStockBySKU.mock.t.Fatalf("StockRepoMock.GetStockBySKU mock is already set by Set")
	}

	if mmGetStockBySKU.defaultExpectation == nil {
		mmGetStockBySKU.defaultExpectation = &StockRepoMockGetStockBySKUExpectation{}
	}

	if mmGetStockBySKU.defaultExpectation.params != nil {
		mmGetStockBySKU.mock.t.Fatalf("StockRepoMock.GetStockBySKU mock is already set by Expect")
	}

	if mmGetStockBySKU.defaultExpectation.paramPtrs == nil {
		mmGetStockBySKU.defaultExpectation.paramPtrs = &StockRepoMockGetStockBySKUParamPtrs{}
	}
	mmGetStockBySKU.defaultExpectation.paramPtrs.ctx = &ctx

	return mmGetStockBySKU
}

// ExpectSkuParam2 sets up expected param sku for IStockRepo.GetStockBySKU
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) ExpectSkuParam2(sku model.SKU) *mStockRepoMockGetStockBySKU {
	if mmGetStockBySKU.mock.funcGetStockBySKU != nil {
		mmGetStockBySKU.mock.t.Fatalf("StockRepoMock.GetStockBySKU mock is already set by Set")
	}

	if mmGetStockBySKU.defaultExpectation == nil {
		mmGetStockBySKU.defaultExpectation = &StockRepoMockGetStockBySKUExpectation{}
	}

	if mmGetStockBySKU.defaultExpectation.params != nil {
		mmGetStockBySKU.mock.t.Fatalf("StockRepoMock.GetStockBySKU mock is already set by Expect")
	}

	if mmGetStockBySKU.defaultExpectation.paramPtrs == nil {
		mmGetStockBySKU.defaultExpectation.paramPtrs = &StockRepoMockGetStockBySKUParamPtrs{}
	}
	mmGetStockBySKU.defaultExpectation.paramPtrs.sku = &sku

	return mmGetStockBySKU
}

// Inspect accepts an inspector function that has same arguments as the IStockRepo.GetStockBySKU
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) Inspect(f func(ctx context.Context, sku model.SKU)) *mStockRepoMockGetStockBySKU {
	if mmGetStockBySKU.mock.inspectFuncGetStockBySKU != nil {
		mmGetStockBySKU.mock.t.Fatalf("Inspect function is already set for StockRepoMock.GetStockBySKU")
	}

	mmGetStockBySKU.mock.inspectFuncGetStockBySKU = f

	return mmGetStockBySKU
}

// Return sets up results that will be returned by IStockRepo.GetStockBySKU
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) Return(sp1 *model.Stock, err error) *StockRepoMock {
	if mmGetStockBySKU.mock.funcGetStockBySKU != nil {
		mmGetStockBySKU.mock.t.Fatalf("StockRepoMock.GetStockBySKU mock is already set by Set")
	}

	if mmGetStockBySKU.defaultExpectation == nil {
		mmGetStockBySKU.defaultExpectation = &StockRepoMockGetStockBySKUExpectation{mock: mmGetStockBySKU.mock}
	}
	mmGetStockBySKU.defaultExpectation.results = &StockRepoMockGetStockBySKUResults{sp1, err}
	return mmGetStockBySKU.mock
}

// Set uses given function f to mock the IStockRepo.GetStockBySKU method
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) Set(f func(ctx context.Context, sku model.SKU) (sp1 *model.Stock, err error)) *StockRepoMock {
	if mmGetStockBySKU.defaultExpectation != nil {
		mmGetStockBySKU.mock.t.Fatalf("Default expectation is already set for the IStockRepo.GetStockBySKU method")
	}

	if len(mmGetStockBySKU.expectations) > 0 {
		mmGetStockBySKU.mock.t.Fatalf("Some expectations are already set for the IStockRepo.GetStockBySKU method")
	}

	mmGetStockBySKU.mock.funcGetStockBySKU = f
	return mmGetStockBySKU.mock
}

// When sets expectation for the IStockRepo.GetStockBySKU which will trigger the result defined by the following
// Then helper
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) When(ctx context.Context, sku model.SKU) *StockRepoMockGetStockBySKUExpectation {
	if mmGetStockBySKU.mock.funcGetStockBySKU != nil {
		mmGetStockBySKU.mock.t.Fatalf("StockRepoMock.GetStockBySKU mock is already set by Set")
	}

	expectation := &StockRepoMockGetStockBySKUExpectation{
		mock:   mmGetStockBySKU.mock,
		params: &StockRepoMockGetStockBySKUParams{ctx, sku},
	}
	mmGetStockBySKU.expectations = append(mmGetStockBySKU.expectations, expectation)
	return expectation
}

// Then sets up IStockRepo.GetStockBySKU return parameters for the expectation previously defined by the When method
func (e *StockRepoMockGetStockBySKUExpectation) Then(sp1 *model.Stock, err error) *StockRepoMock {
	e.results = &StockRepoMockGetStockBySKUResults{sp1, err}
	return e.mock
}

// Times sets number of times IStockRepo.GetStockBySKU should be invoked
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) Times(n uint64) *mStockRepoMockGetStockBySKU {
	if n == 0 {
		mmGetStockBySKU.mock.t.Fatalf("Times of StockRepoMock.GetStockBySKU mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetStockBySKU.expectedInvocations, n)
	return mmGetStockBySKU
}

func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) invocationsDone() bool {
	if len(mmGetStockBySKU.expectations) == 0 && mmGetStockBySKU.defaultExpectation == nil && mmGetStockBySKU.mock.funcGetStockBySKU == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetStockBySKU.mock.afterGetStockBySKUCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetStockBySKU.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetStockBySKU implements stock.IStockRepo
func (mmGetStockBySKU *StockRepoMock) GetStockBySKU(ctx context.Context, sku model.SKU) (sp1 *model.Stock, err error) {
	mm_atomic.AddUint64(&mmGetStockBySKU.beforeGetStockBySKUCounter, 1)
	defer mm_atomic.AddUint64(&mmGetStockBySKU.afterGetStockBySKUCounter, 1)

	if mmGetStockBySKU.inspectFuncGetStockBySKU != nil {
		mmGetStockBySKU.inspectFuncGetStockBySKU(ctx, sku)
	}

	mm_params := StockRepoMockGetStockBySKUParams{ctx, sku}

	// Record call args
	mmGetStockBySKU.GetStockBySKUMock.mutex.Lock()
	mmGetStockBySKU.GetStockBySKUMock.callArgs = append(mmGetStockBySKU.GetStockBySKUMock.callArgs, &mm_params)
	mmGetStockBySKU.GetStockBySKUMock.mutex.Unlock()

	for _, e := range mmGetStockBySKU.GetStockBySKUMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmGetStockBySKU.GetStockBySKUMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetStockBySKU.GetStockBySKUMock.defaultExpectation.Counter, 1)
		mm_want := mmGetStockBySKU.GetStockBySKUMock.defaultExpectation.params
		mm_want_ptrs := mmGetStockBySKU.GetStockBySKUMock.defaultExpectation.paramPtrs

		mm_got := StockRepoMockGetStockBySKUParams{ctx, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetStockBySKU.t.Errorf("StockRepoMock.GetStockBySKU got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmGetStockBySKU.t.Errorf("StockRepoMock.GetStockBySKU got unexpected parameter sku, want: %#v, got: %#v%s\n", *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetStockBySKU.t.Errorf("StockRepoMock.GetStockBySKU got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetStockBySKU.GetStockBySKUMock.defaultExpectation.results
		if mm_results == nil {
			mmGetStockBySKU.t.Fatal("No results are set for the StockRepoMock.GetStockBySKU")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmGetStockBySKU.funcGetStockBySKU != nil {
		return mmGetStockBySKU.funcGetStockBySKU(ctx, sku)
	}
	mmGetStockBySKU.t.Fatalf("Unexpected call to StockRepoMock.GetStockBySKU. %v %v", ctx, sku)
	return
}

// GetStockBySKUAfterCounter returns a count of finished StockRepoMock.GetStockBySKU invocations
func (mmGetStockBySKU *StockRepoMock) GetStockBySKUAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStockBySKU.afterGetStockBySKUCounter)
}

// GetStockBySKUBeforeCounter returns a count of StockRepoMock.GetStockBySKU invocations
func (mmGetStockBySKU *StockRepoMock) GetStockBySKUBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStockBySKU.beforeGetStockBySKUCounter)
}

// Calls returns a list of arguments used in each call to StockRepoMock.GetStockBySKU.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetStockBySKU *mStockRepoMockGetStockBySKU) Calls() []*StockRepoMockGetStockBySKUParams {
	mmGetStockBySKU.mutex.RLock()

	argCopy := make([]*StockRepoMockGetStockBySKUParams, len(mmGetStockBySKU.callArgs))
	copy(argCopy, mmGetStockBySKU.callArgs)

	mmGetStockBySKU.mutex.RUnlock()

	return argCopy
}

// MinimockGetStockBySKUDone returns true if the count of the GetStockBySKU invocations corresponds
// the number of defined expectations
func (m *StockRepoMock) MinimockGetStockBySKUDone() bool {
	if m.GetStockBySKUMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetStockBySKUMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetStockBySKUMock.invocationsDone()
}

// MinimockGetStockBySKUInspect logs each unmet expectation
func (m *StockRepoMock) MinimockGetStockBySKUInspect() {
	for _, e := range m.GetStockBySKUMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StockRepoMock.GetStockBySKU with params: %#v", *e.params)
		}
	}

	afterGetStockBySKUCounter := mm_atomic.LoadUint64(&m.afterGetStockBySKUCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetStockBySKUMock.defaultExpectation != nil && afterGetStockBySKUCounter < 1 {
		if m.GetStockBySKUMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StockRepoMock.GetStockBySKU")
		} else {
			m.t.Errorf("Expected call to StockRepoMock.GetStockBySKU with params: %#v", *m.GetStockBySKUMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetStockBySKU != nil && afterGetStockBySKUCounter < 1 {
		m.t.Error("Expected call to StockRepoMock.GetStockBySKU")
	}

	if !m.GetStockBySKUMock.invocationsDone() && afterGetStockBySKUCounter > 0 {
		m.t.Errorf("Expected %d calls to StockRepoMock.GetStockBySKU but found %d calls",
			mm_atomic.LoadUint64(&m.GetStockBySKUMock.expectedInvocations), afterGetStockBySKUCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StockRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetStockBySKUInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StockRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StockRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetStockBySKUDone()
}
